version: "3.8"

services:
  database:
    container_name: database
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=crud
    ports:
      - 7070:5432
    volumes:
      - db:/var/lib/postgresql/data
    command: postgres -c log_statement=all

volumes:
  db:
